import { jsPDF } from 'jspdf';
import { IncidentReportSummary } from './reportGenerator';

export function exportIncidentReportPdf(report: IncidentReportSummary) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  let cursorY = 18;

  // Header Banner
  doc.setFillColor(11, 87, 208); // #0B57D0
  doc.rect(margin, cursorY, contentWidth, 20, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('FRAUD FIRST-AID | FIRST-HOUR INCIDENT DOCKET', margin + 6, cursorY + 8);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.text('Emergency Decision Support Summary for 1930 & National Cyber Crime Reporting Portal', margin + 6, cursorY + 14);

  cursorY += 26;

  // Metadata Bar
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, cursorY, contentWidth, 14, 2, 2, 'FD');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(`Ref ID: ${report.incidentId}`, margin + 4, cursorY + 6);
  doc.text(`Generated: ${report.generatedAt}`, margin + 4, cursorY + 11);

  doc.setTextColor(255, 59, 48); // Red emergency flag
  doc.text('PRIORITY: EMERGENCY 1930 DISPATCH', pageWidth - margin - 65, cursorY + 8);

  cursorY += 20;

  // Section 1: Incident & Complainant Details
  doc.setTextColor(11, 87, 208);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('1. Incident & Complainant Overview', margin, cursorY);
  cursorY += 6;

  doc.setTextColor(51, 65, 85);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');

  const overviewRows = [
    ['Incident Category:', report.categoryTitle],
    ['Complainant Name:', report.victimName || 'N/A'],
    ['Contact Phone:', report.victimPhone || 'N/A'],
    ['Incident Date & Time:', report.dateTime || 'Within last hour'],
    ['Total Amount Lost:', report.amountLost],
    ['Money Debited/Transferred:', report.moneyTransferred],
    ['Primary Bank/Wallet:', report.bankName],
    ['Transaction ID / 12-Digit UTR:', report.utrNumber],
  ];

  overviewRows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, margin + 4, cursorY);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value), margin + 65, cursorY);
    cursorY += 5.5;
  });

  cursorY += 4;

  // Section 2: Scenario Evidence Identifiers
  doc.setTextColor(11, 87, 208);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('2. Scenario Evidence & Suspect Identifiers', margin, cursorY);
  cursorY += 6;

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);

  if (report.scenarioSpecificPoints.length > 0) {
    report.scenarioSpecificPoints.forEach((point) => {
      doc.text(`• ${point}`, margin + 4, cursorY);
      cursorY += 5;
    });
  } else {
    doc.text('• Standard digital evidence to be preserved by victim.', margin + 4, cursorY);
    cursorY += 5;
  }

  cursorY += 4;

  // Section 3: First-Hour Actions Record
  doc.setTextColor(11, 87, 208);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('3. First-Hour Actions Audit Trail', margin, cursorY);
  cursorY += 6;

  doc.setFontSize(8.5);
  doc.setTextColor(16, 185, 129); // Green completed
  report.actionsTaken.forEach((act) => {
    doc.text(`[✓ COMPLETED] ${act}`, margin + 4, cursorY);
    cursorY += 5;
  });

  doc.setTextColor(220, 38, 38); // Red pending
  report.actionsPending.forEach((act) => {
    doc.text(`[  PENDING  ] ${act}`, margin + 4, cursorY);
    cursorY += 5;
  });

  cursorY += 6;

  // Section 4: Instructions for Official Authorities
  doc.setFillColor(238, 242, 255);
  doc.setDrawColor(199, 210, 254);
  doc.roundedRect(margin, cursorY, contentWidth, 22, 2, 2, 'FD');

  doc.setTextColor(30, 58, 138);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Immediate Official Escalation Pathways:', margin + 4, cursorY + 5.5);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('1. Call 1930 (Citizen Financial Cyber Fraud Reporting System) with the 12-digit UTR to trigger beneficiary hold.', margin + 4, cursorY + 10.5);
  doc.text('2. Lodge complaint ticket on https://cybercrime.gov.in within 24 hours attaching this incident summary.', margin + 4, cursorY + 15);
  doc.text('3. Submit copy to Bank Branch Manager to invoke RBI Zero/Limited Customer Liability guidelines.', margin + 4, cursorY + 19.5);

  cursorY += 28;

  // Footer Disclaimer
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(7.5);
  doc.text('Generated by Fraud First-Aid (Team Alpha Analysts) • Prototype for Ideathon & Rapid First-Hour Public Assistance.', margin, cursorY);
  doc.text('Fraud First-Aid guides immediate first actions; actual investigation & recovery is executed by designated cyber cells & banks.', margin, cursorY + 4);

  doc.save(`Fraud_First_Aid_Report_${report.incidentId}.pdf`);
}
